[project]
name = 'LocalNewsChain-Truth-Network'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.fact-checking-coordination]
path = 'contracts/fact-checking-coordination.clar'
clarity_version = 3
epoch = '3.2'

[contracts.local-journalist-registry]
path = 'contracts/local-journalist-registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.misinformation-prevention-system]
path = 'contracts/misinformation-prevention-system.clar'
clarity_version = 3
epoch = '3.2'

[contracts.truth-journalism-rewards]
path = 'contracts/truth-journalism-rewards.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
